### ISSUE TITLE
Inconsistent exported animations

### ISSUE THREAD

**Issue by Barnacle** [Barnacle/USF4-Character-Extractor#2]
Exported animations varies from good to partially broken. The best way is to export a single animation after the model loads. Otherwise it depends on other selected animations.
https://github.com/Barnacle/USF4-Character-Extractor/issues/2#issuecomment-591406535

**Comment by Tosyk** [comment]
можно это как то починить?
![image](https://user-images.githubusercontent.com/24209966/75121499-a8372400-56a5-11ea-8db7-23fff5d31770.png)

**Comment by Barnacle** [comment]
@Tosyk У модели нужно заменить стандартный скелет на скелет из файла анимации. Делается это через Settings -> Replace Skeleton. Если персонаж не в T-позе, а в позе звезды, то нужно добавить ещё и галочку Star-Pose fix.

**Comment by Tosyk** [comment]
ого! класс! всё работает! можно ли как-то удалять автоматически первый кадр анимаций, который ставит все анимации в референсную позу?

**Comment by Barnacle** [comment]
Увы, это я так и не добавил. Собственно по этому кадру я и пытался понять причину того, что на скриншоте.
Но можно закомментировать этот кадр здесь: 
https://github.com/Barnacle/USF4-Character-Extractor/blob/d44a370ee5b1b1ef73612f88a17105617aca6bf6/main/main.h#L1206

**Comment by Tosyk** [comment]
а вы можете собрать такую версию? чтобы первого кадра не было? или вы уже не занимаетесь этим проектом? мне кажется всем было бы полезно НЕ иметь этот первый референсный кадр в анимации :)

**Comment by Barnacle** [comment]
Да это такой себе проект... больше эксперимент, который по итогу должен был отправиться в корзину 5 лет назад.
Версию собрал - https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.2e
Но на самом деле, это было бы действительно полезно, если бы не изначальный баг, по поводу которого и был создан этот тикет. Экспортировать вообще все анимации за один проход - не идеальный вариант, т.к. анимации в какой-то момент начинают ломаться, чего не наблюдается при экспорте одной или нескольких после загрузки модели. Отрезать первый кадр в редакторе было делом не слишком трудозатратным. :)

**Comment by Tosyk** [comment]
я не знаю где ещё написать, поэтому напишу тут: я проверил и прога работает с Street Fighter x Tekken без проблем. только текстуры не извлекаются, прога их как будто не видит:
![image](https://user-images.githubusercontent.com/24209966/75201075-8d81af80-5778-11ea-9c56-6611999e4e10.png)

**Comment by Barnacle** [comment]
Вряд ли вспомню причину, но их можно выдрать с помощью sf4viewer. Вроде бы там не было с ними проблем. За исключением, что сами текстуры в SFxT скорее не текстуры, а маски.
https://sourceforge.net/projects/sf4viewer/

**Comment by Tosyk** [comment]
огромное вам спасибо! тулза просто прекрасна! сегодня после работы ещё раз проверю анимации. но пока это самое отличное для SF что есть - просто идеально!

p.s: а вы реверсингом других игр не занимаетесь? или это была просто проверка возможностей? я уже очень давно хочу достать модели из Red Dead Revolver — текстуры сконвертировать можно, а вот модели лежат в MOD+SKEL файлах.

**Comment by Barnacle** [comment]
Да, это была проверкой возможностей, первым и единственным опытом в написании экспортёра. Самим реверсингом с нуля в данном случае не занимался, а пользовался уже имевшейся информацией и кодом.

**Comment by Tosyk** [comment]
regarding the bug: I've tested many animations by converting SMD to FBX (with noesis) and load them into 3ds max. See no issue at all.
so batch animation export do not brakes any animations

**Comment by Barnacle** [comment]
This is how it looks.

JRI_DEM_APPEAL_10 single export:
![1](https://user-images.githubusercontent.com/4092092/75345076-908eb400-58ce-11ea-8945-fc59d52990e5.png)

JRI_DEM_APPEAL_10 export all:
![2](https://user-images.githubusercontent.com/4092092/75345098-a00dfd00-58ce-11ea-81fb-2c23d4eb3f17.png)

Actually this is a bug from sf4viewer, as EMA code was taken directly from it.
Same behaviour, when you're scrolling through animation list.
![3](https://user-images.githubusercontent.com/4092092/75345268-f5e2a500-58ce-11ea-98bc-7d1e3fc8a859.png)

But sometimes it may be even worse, when (for example) arm rotated in a different direction.
![4](https://user-images.githubusercontent.com/4092092/75447813-abc7f500-599c-11ea-9f66-e37437e9e593.png)

The super lazy fix for it is to reload animation file every time, but the exporting process will be very long.
So I never took a closer look at this bug...

**Comment by Tosyk** [comment]
for some reason now ALL animations looks broken if I DON'T use:
![image](https://user-images.githubusercontent.com/24209966/75388238-aebbda80-58f5-11ea-958f-d7efe4d5b723.png)
and get this:
![image](https://user-images.githubusercontent.com/24209966/75388293-c3986e00-58f5-11ea-8169-c83428385e8f.png)

but if I use it I get this:
![image](https://user-images.githubusercontent.com/24209966/75388377-e460c380-58f5-11ea-913a-bd61926b8836.png)

It worked fine yesterday, but now it doesn't work.. why?

**Comment by Barnacle** [comment]
Because I forgot about RLegRoot/LLegRoot/LArmRoot/RArmRoot nodes.
Should be fine now.
https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.2e

**Comment by Barnacle** [comment]
Because I forgot about RLegRoot/LLegRoot/LArmRoot/RArmRoot nodes.
Should be fine now.
https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.2e

**Comment by Tosyk** [comment]
so I've checked several model animations (XXX.obj.ema) - they all brakes after 72.
so 72nd animation is good, but 73rd and all further ones are all broken

any thoughts on that? I could test more if needed

**Comment by Barnacle** [comment]
The only quick thing I can do as a temporal solution is to re-setup EMA file on each animation. This will be a slower process, but working.
Not sure I'm gonna debug sf4viewer's EMA code myself in the near future. It definitely requires to reinitialize or clean something during cycling through animations. But again, I never was too much into it.

App has been updated again.
https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.2e

**Comment by Tosyk** [comment]
appreciate you taking a look into it so fast. re-setup EMA file is the solid sollution, even if it's will not be quick converting! I'm going to test it later today.

once again, animation is brakes between 72 and 73 entry. I think it does for every character — doesn't matter if I export all or just all XXX.obj.ema animations. it's okay for other animation type (camera, face, etc) because there's not too many animations.

**Comment by Barnacle** [comment]
Ah, yeah. It seems, that every character also has a couple of animations from other characters. Maybe those are reused, or just garbage, not sure.
sf4viewer is having issues with 'em too.

DSM_DMG_BURN_CROUCH (Dhalsim's animation), RYU_DMG_BURN_JUMP (Ryu's animation) - usually they are around 72-73 entry. Sometimes there are more Ryu's animations around 150 entry.

Every other animation with the current character prefix seems works fine as expected.

**Comment by Tosyk** [comment]
I mean that all the animations 1-72 are fine but all after that 73+ are broken. maybe that give you some idea

**Comment by Barnacle** [comment]
What tools are you using? And how it looks?
I'm using "Blender 2.82" and "Blender Source Tools 3.0.3". I checked it and it works fine for me.

**Comment by Tosyk** [comment]
I'm using 3ds max 2009 x32 + converting SMD into FBX with Noesis.
sorry, what's working for you?

**Comment by Barnacle** [comment]
I mean, that only reused animations in *.obj.ema are "broken" for me.
For example, Juri animations:
1-72 - JRI_ anims are fine
73-74 - DSM_ and RYU_ anims are kinda broken with the imported model
75-159 - JRI_ and CNL_DEM_ anims are fine

I've checked few other characters and the results are the same.

I never tried Noesis, so I can't say for sure if it's something wrong there during conversion.
BTW, a bit unrelated, but still. I remember I tried to import SMDs in Softimage using official addon from Valve, and it didn't work properly or just crashed. Only Blender Source Tools helped me with it.

**Comment by Tosyk** [comment]
> 75-159 - JRI_ and CNL_DEM_ anims are fine

those are also broken for me for many characters. I can check more :)
about noesis I can assume that it work good for converting SMD2FBX. I use it for about 10 years

**Comment by Barnacle** [comment]
I'm still not sure what do you mean by "broken".

So...
1) I exported all animations.
2) Downloaded Noesis and didn't notice any issue in it's viewport.
3) Exported model and random 80+ animation as FBX.
4) Imported both in Maya 2017 and didn't notice any issue there too.

Again the same animation "150. JRI_DEM_APPEAL_10", same frame. Works as expected.
![maya](https://user-images.githubusercontent.com/4092092/75561875-477b6300-5a7a-11ea-8e1a-02d96e8491e0.png)

I don't know. Maybe 3ds max 2009 is too outdated for this then. Or something else.

**Comment by Tosyk** [comment]
alright, I tested latest version. seems like now I have issue only with 73. DSM_DMG_BURN_CROUCH.smd:
![image](https://user-images.githubusercontent.com/24209966/75590769-296c2d80-5a8f-11ea-9926-de7cb30c9e03.png)

and it's same even if I export only this animation

**Comment by Barnacle** [comment]
So it's working fine after all. :P

sf4viewer is rendering it the same way.
![1](https://user-images.githubusercontent.com/4092092/75593255-5d5b4900-5ab7-11ea-898b-8982915c42ef.png)

I doubt that this bug even needs a fix, because as I mentioned these 2 animations are from other characters, not related to a current one. No idea why those are existing in every animation file. Obviously nobody is using Dhalsim's burning crouch stance like this in game, and I do not remember that even Dhalsim is using it, because it's slow as hell. So it's rather some garbage, or used as a placeholder during development.

In other words just ignore 'em.

**Comment by Barnacle** [comment]
Fixed in 014c2b3b65b642c7993439dc8603ef77594a330f
