### ISSUE TITLE
can't run application

### ISSUE THREAD

**Issue by startmuscle0731** [Barnacle/USF4-Character-Extractor#4]
I'm trying to start the exe, but it doesn't run. In particular, it seems that no error message is displayed. The same is true if you build it yourself. I have the DX9 runtime installed, but I don't know what caused it.

**Comment by startmuscle0731** [comment]
just symbolic error

**Comment by Barnacle** [comment]
Oh, sorry, I didn't notice this opened issue.
A symbolic error? How did you solve it? :thinking:
