### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Ghellt** [Barnacle/USF4-Character-Extractor#7]
![unknown32](https://user-images.githubusercontent.com/93708559/140303540-a6a896b6-06ca-42c8-8ca9-2833162fb489.png)

Hello ! I can't run the program, this error appears every time I run the program from Microsoft Viusal Studio.

**Comment by Barnacle** [comment]
Hello. Are your sure you even compiled the program? Better check the build output for the issue.
Current dependencies are: [DX SDK](https://www.microsoft.com/en-us/download/details.aspx?id=6812) and .Net 4.5 targeting pack.

**Comment by Ghellt** [comment]
Yes like i got this 
![image](https://user-images.githubusercontent.com/93708559/140312830-2a0a0e58-da55-4fcf-90b5-a8c7c984c033.png)
and i have the latest version of Net
![image](https://user-images.githubusercontent.com/93708559/140313001-bb23168a-59e7-4b14-8c12-ff9f4a4f26bd.png)
So i don't know how to fix that

**Comment by Ghellt** [comment]
maybe it's the game folder location ? cause i havent instal in my main hard drive i downloaded on other hard drive that is in my pc

**Comment by Barnacle** [comment]
What is in your build output in console? Because obviously you're trying to start the app in debug mode inside Visual Studio, but the executable doesn't exist in `C:\Users\...\Debug\`. Guess it's failed to compile.

.Net Runtime is not the same as Targeting Pack. You need to install it in VS Installer
![1](https://user-images.githubusercontent.com/4092092/140338193-3f2c13a1-bf32-41b7-be9e-d9197bd0c1c0.png)

Also you need to install legacy DX SDK, cause the app is not compatible with Windows 10 SDK.

**Comment by Barnacle** [comment]
Ok, I think I get it. I didn't notice, that you have `SSF4mv.exe` in your path, which is not correct.
You're trying to debug `d3d.dll` in Visual Studio. Right-click on `USF4ce` project and click "Set as Startup Project".

**Comment by Ghellt** [comment]
Okay, i started what you said to me 
![image](https://user-images.githubusercontent.com/93708559/140382892-caf1226e-f28e-4ca4-9ca3-c74e02337946.png)
but that do nothing

**Comment by Ghellt** [comment]
and i have that 
![image](https://user-images.githubusercontent.com/93708559/140383156-1d4f0be3-c799-4c71-a5eb-e0ec848452ad.png)
![image](https://user-images.githubusercontent.com/93708559/140383168-7aee9033-ef98-4930-8e26-8dd7d5c79fdf.png)
![image](https://user-images.githubusercontent.com/93708559/140383184-eee2346e-e96b-429c-bdce-30cf4ba5ab31.png)
![image](https://user-images.githubusercontent.com/93708559/140383211-116792d3-cc9c-439c-a807-60b7301d16b9.png)
![image](https://user-images.githubusercontent.com/93708559/140383215-c467b747-7985-4dc1-b538-c6660e8b67db.png)

**Comment by Ghellt** [comment]
I tried but that do nothing 
![image](https://user-images.githubusercontent.com/93708559/140383455-3726aef0-9f78-4eda-b38e-97023ef68dc8.png)
and i got that
![image](https://user-images.githubusercontent.com/93708559/140383508-41457a7f-bc86-4067-a0a9-5d0fe9122395.png)
![image](https://user-images.githubusercontent.com/93708559/140383530-dd490515-2297-4974-932f-019f55c0f28f.png)
![image](https://user-images.githubusercontent.com/93708559/140383544-8e0f58f3-dbaf-4178-97eb-4a78489376ad.png)
![image](https://user-images.githubusercontent.com/93708559/140383566-ece80373-6a6c-486a-a6ea-7f9f2c6c6a92.png)
![image](https://user-images.githubusercontent.com/93708559/140383587-6d5fff53-d42e-4a4c-8eeb-5ee92f2cfb4d.png)
![image](https://user-images.githubusercontent.com/93708559/140383595-ed78b9ed-a2a9-4249-94b7-a86d3895adf8.png)

**Comment by Ghellt** [comment]
i instal the .NET with the good version but always the same thing

**Comment by Barnacle** [comment]
I will ask you again: can you provide build log, please?
![1](https://user-images.githubusercontent.com/4092092/140398130-15a54b11-699e-4d3d-957e-d3b6b0950012.png)

Otherwise I'm gonna close this issue, because it doesn't look like a real issue, but more like a lack of experience, sorry.

**Comment by Ghellt** [comment]
I dont know where it is cause i dont use this, i just wanted to open the application and take 3d model but it's more complicated
than i tought

**Comment by Barnacle** [comment]
In this case there is no need to build the source code on your own.
Compiled application available here: https://github.com/Barnacle/USF4-Character-Extractor/releases/tag/0.3c
Just download and unpack [Release.zip](https://github.com/Barnacle/USF4-Character-Extractor/releases/download/0.3c/Release.zip). Cheers.

**Comment by Ghellt** [comment]
Thanks it works
