### ISSUE TITLE
No hair and accessories animation

### ISSUE THREAD

**Issue by Kiwi1444** [Barnacle/USF4-Character-Extractor#8]
I don't know how the game engine is organized, so I ask this question. Lack of animation of hair and clothing accessories is the norm when exporting? For example, Poison's hair and hancuffs. Are these animations missing from the game files originally? In this case, the hair and accessories must be animated by the game's physics engine and if the model is exported to Blender, for example, the hair and accessories must be animated by the user himself. Do I understand it correctly?

**Comment by Barnacle** [comment]
Yep, that's correct. No physics animations inside anim files. Cloth, hair, etc. physics are handled by game's engine.

**Comment by Kiwi1444** [comment]
Thank you for quick reply and good program.
